# Set up XDG paths
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export CONFIGDIR="${HOME}/.config"
export ZDOTDIR="$CONFIGDIR/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

export EDITOR="vim"
export VISUAL="vim"

export GPG_TTY=`tty`
